### ISSUE TITLE
TypeError: opt.init is not a function

### ISSUE THREAD

**Issue by bestony** [CFETeam/cos_node#1]
```
C:\Users\Bestony\Desktop\cos\node_modules\cos-sdk\lib\util.js:37
    opt.init(defaultValue);
        ^

TypeError: opt.init is not a function
    at initOpt (C:\Users\Bestony\Desktop\cos\node_modules\cos-sdk\lib\util.js:37
:9)
    at Object._signUrl (C:\Users\Bestony\Desktop\cos\node_modules\cos-sdk\cos.js
:129:21)
    at Object.request (C:\Users\Bestony\Desktop\cos\node_modules\cos-sdk\cos.js:
155:24)
    at Object.listBucket (C:\Users\Bestony\Desktop\cos\node_modules\cos-sdk\lib\
api\bucket.js:41:10)
    at Object.exports.list [as lsBucket] (C:\Users\Bestony\Desktop\cos\node_modu
les\cos-sdk\lib\api\bucket.js:107:16)
    at Object.<anonymous> (C:\Users\Bestony\Desktop\cos\app.js:9:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
代码
```
var Cos = require("cos-sdk"); 
var cos = new Cos({
    accessId: "", 
    secretId: "",
    secretKey: "" 
});
cos.lsBucket(function(e) {
    console.log(e);
});
```

**Comment by fakaka** [comment]
我也是。。。
